<a href="https://colab.research.google.com/github/sinngam-khaidem/Deep-Learning-with-Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

True
tensor([[0.2877, 0.9990],
        [0.5960, 0.7621]])


# Tensors
Multidimensional arrays. Every tensor has a rank.\
Scaler - Rank 0 tensor\
Vector - Rank 1 tensor\
n * n matrix - Rank 2 tensor


In [3]:
# Tensor from lists
x = torch.tensor([[0,0,1], [1,1,1], [0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

Tensor elements can be changeed using python indexing.

In [4]:
x[0][1] = -5555
x

tensor([[    0, -5555,     1],
        [    1,     1,     1],
        [    0,     0,     0]])

torch.ones(n,m), torch.zeros(n, m) - Create tensors filled with 1's and 0's

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

We can do standard math ops with tensors.

In [9]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

Value of tensor with rank 0 can be pullled out using item()

In [12]:
x = torch.rand(1)
x.item()

0.2747945785522461

Tensors can either live on CPU or GPU. It can be copied between devices using to() function.

In [2]:
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [3]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

## Tensor Operations

Finding the maximum item in a tensor - max()\
Finding the index that contains maximum value - argmax()

In [7]:
torch.rand(2,2).max()

tensor(0.7592)

In [5]:
torch.rand(2,2).max().item()

0.6985429525375366

Changing the type of a tensor

In [9]:
long_tensor = torch.tensor([[0,0,1], [1,1,1], [0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [10]:
float_tensor = torch.tensor([[0,0,1], [1,1,1], [0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

Most functions that operate on tensor and return a tensor create a new tensor to store the results. If we want to save memory, we can look to see if an in-place function is defined. It has the same name as the original function but with an appeded underscore.

In [11]:
random_tensor = torch.rand(2,2)
random_tensor.log2()

tensor([[-0.4188, -0.8251],
        [-0.1884, -0.7878]])

In [12]:
random_tensor.log2_()

tensor([[-0.4188, -0.8251],
        [-0.1884, -0.7878]])

## Reshaping tensors
MNIST dataset of handwritten digits is a collection of 28x28 images.<br>
But it is packaged in arrays of length 784.<br>
We need to turn those back to 1x28x28 tensors\(Number of channels, Number of rows, Number of columns).<br>
We can do this using view() or reshape().<br>
**Note**: Reshaped tensor has to have the same number of total elements as the original.

In [17]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [18]:
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

### view() vs reshape()
**view()** operates as a view of the original tensor. If underlying data is changed, view will change too. \
**view()** can throw error if the underlying view is not *contiguous*. \
If this happens call **tensor.contiguous()** before calling **view()**. \
**reshape()** does all these behind the scenes




### Rearranging dimensions of a tensor.

In [19]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])

## Tensor Broadcasting
Helps us in performing operations between a tensor and a smaller tensor.
https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics \

### General semantics
Two tensors are “broadcastable” if the following rules hold:

1. Each tensor has at least one dimension.

2. When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

### Calculation of resulting tensor
If two tensors x, y are **“broadcastable”**, the resulting tensor size is calculated as follows:

1. If the number of dimensions of x and y are not equal, prepend 1 to the dimensions of the tensor with fewer dimensions to make them equal length.

2. Then, for each dimension size, the resulting dimension size is the max of the sizes of x and y along that dimension.

In [22]:
# can line up trailing dimensions to make reading easier
x=torch.empty(5,1,4,1)
y=torch.empty(  3,1,1)
(x+y).size()

torch.Size([5, 3, 4, 1])

In [24]:
x=torch.empty(5,2,4,1)
y=torch.empty(  3,1,1)
(x+y).size()

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1